Repository OSGeo/PROJ, pull requests merged in 2020-03, with the labels that each got.

#2005 Fix bad copy&replace pattern on HEALPix and rHEALPix projection names
  src/projections/healpix.cpp
Labels: backport 6.3, backport 7.0

#2008 Fix download link for proj-data 1.0
  docs/source/download.rst
Labels: backport 7.0

#2011 createUnitOfMeasure(): use full double resolution for the conversion factor
  src/iso19111/factory.cpp
  test/unit/test_factory.cpp
Labels: backport 6.3, backport 7.0

#2015 Update README with info on PROJ-data
  README.md
Labels: backport 7.0

#2010 Document Autotools and CMake configure options
  docs/source/install.rst
Labels: Documentation, backport 7.0

#2019 Remove occurences of deprecated PROJ.4 syntax
  docs/source/operations/projections/cass.rst
  docs/source/operations/projections/ccon.rst
  docs/source/operations/projections/eqc.rst
  docs/source/operations/projections/gall.rst
  docs/source/operations/projections/tmerc.rst
Labels: backport 7.0

#2037 fix documentation for proj_trans_generic()
  docs/source/development/reference/functions.rst
Labels: backport 7.0

#2026 utm/ups: make sure to set errno to PJD_ERR_ELLIPSOID_USE_REQUIRED if es==0
  docs/source/operations/projections/utm.rst
  src/projections/stere.cpp
  src/projections/tmerc.cpp
  test/gie/builtins.gie
Labels: backport 7.0

#2044 data/Makefile.am: remove bashism
  data/Makefile.am
Labels: backport 6.3, backport 7.0

#2046 Doc: use 'ellipsoidal' to refer to the ellipsoidal formulation (to be opposed to the spherical one)
  docs/source/operations/projections/aea.rst
  docs/source/operations/projections/aeqd.rst
  docs/source/operations/projections/alsk.rst
  docs/source/operations/projections/bonne.rst
  docs/source/operations/projections/calcofi.rst
  docs/source/operations/projections/cass.rst
  docs/source/operations/projections/cea.rst
  docs/source/operations/projections/eqdc.rst
  docs/source/operations/projections/geos.rst
  docs/source/operations/projections/gn_sinu.rst
  docs/source/operations/projections/gs48.rst
  docs/source/operations/projections/gs50.rst
  docs/source/operations/projections/healpix.rst
  docs/source/operations/projections/imw_p.rst
  docs/source/operations/projections/krovak.rst
  docs/source/operations/projections/labrd.rst
  docs/source/operations/projections/laea.rst
  docs/source/operations/projections/lagrng.rst
  docs/source/operations/projections/lcc.rst
  docs/source/operations/projections/lcca.rst
  docs/source/operations/projections/leac.rst
  docs/source/operations/projections/lee_os.rst
  docs/source/operations/projections/lsat.rst
  docs/source/operations/projections/mbtfps.rst
  docs/source/operations/projections/merc.rst
  docs/source/operations/projections/mil_os.rst
  docs/source/operations/projections/misrsom.rst
  docs/source/operations/projections/ob_tran.rst
  docs/source/operations/projections/omerc.rst
  docs/source/operations/projections/poly.rst
  docs/source/operations/projections/qsc.rst
  docs/source/operations/projections/rhealpix.rst
  docs/source/operations/projections/rouss.rst
  docs/source/operations/projections/sinu.rst
  docs/source/operations/projections/stere.rst
  docs/source/operations/projections/sterea.rst
  docs/source/operations/projections/tmerc.rst
  docs/source/operations/projections/utm.rst
Labels: backport 7.0

#2056 .cirrus.yml: disable ccache as cache uploading can be super slow
  .cirrus.yml
Labels: backport 7.0

#2053 ProjectedCRS::identify(): tune it to better work with ESRI WKT representation of EPSG:2193
  src/iso19111/crs.cpp
  test/unit/test_crs.cpp
Labels: backport 6.3, backport 7.0

#2060 Add note about orientation of control points in `chamb`
  docs/source/operations/projections/chamb.rst
Labels: backport 7.0

#2063 Fix build with gcc 4.8.5 (fixes #2062)
  src/grids.cpp
Labels: backport 7.0

#2067 Autotools/pkg-conf: Define datarootdir
  configure.ac
  proj.pc.in
Labels: backport 7.0, bug

#2073 Fix build with libtiff master (libtiff > 4.1.0)
  src/grids.cpp
Labels: backport 7.0

#2065 Add proj_get_units_from_database() (fixes #2004)
  data/sql/customizations.sql
  data/sql/proj_db_table_defs.sql
  data/sql/unit_of_measure.sql
  docs/source/development/reference/functions.rst
  include/proj/io.hpp
  scripts/build_db.py
  src/apps/cs2cs.cpp
  src/apps/geod.cpp
  src/apps/geod_set.cpp
  src/apps/proj.cpp
  src/conversions/unitconvert.cpp
  src/init.cpp
  src/iso19111/c_api.cpp
  src/iso19111/common.cpp
  src/iso19111/factory.cpp
  src/proj.h
  src/proj_internal.h
  src/units.cpp
  test/unit/gie_self_tests.cpp
  test/unit/test_c_api.cpp
  test/unit/test_factory.cpp
Labels: enhancement

#2068 Add proj_get_suggested_operation()
  src/4D_api.cpp
  src/iso19111/c_api.cpp
  src/proj.h
  src/proj_internal.h
  test/unit/test_c_api.cpp
Labels: enhancement

#2075 Align install.rst with current version
  HOWTO-RELEASE
  docs/source/conf.py
  docs/source/install.rst
  docs/source/resource_files.rst
Labels: backport 7.0

#2080 cs2cs: don't require +to for '{source_crs} {target_crs} filename...' syntax (fixes #2012)
  docs/source/apps/cs2cs.rst
  src/apps/cs2cs.cpp
  test/cli/testvarious
  test/cli/tv_out.dist
Labels: backport 7.0

#2082 CMake: fix bug with find_package(PROJ) with macOS
  cmake/project-config-version.cmake.in
Labels: backport 7.0

#2088 ESRI WKT import / identification: special case for NAD_1983_HARN_StatePlane_Colorado_North_FIPS_0501 with Foot_US unit (fixes #2086)
  src/iso19111/coordinateoperation.cpp
  src/iso19111/io.cpp
  test/unit/test_crs.cpp
Labels: backport 7.0

#2090 EngineeringCRS: when exporting to WKT1_GDAL, output unit and axis (fixes https://github.com/OSGeo/gdal/issues/2347)
  src/iso19111/crs.cpp
  test/unit/test_c_api.cpp
  test/unit/test_crs.cpp
  test/unit/test_io.cpp
Labels: backport 6.3, backport 7.0

#2097 Use jtsk03-jtsk horizontal grid from CDN
  data/sql/grid_alternatives.sql
Labels: backport 7.0

#2102 Fixes wrong grids file name in esri.sql
  data/sql/grid_alternatives.sql
Labels: backport 7.0

#2105 Fix identification of projected CRS whose name is close but not strictly equal to a ESRI alias (fixes #2099)
  src/iso19111/crs.cpp
  test/unit/test_crs.cpp
Labels: backport 7.0

#2100 CMake: prefer to use use PROJ_SOURCE_DIR and PROJ_BINARY_DIR
  CMakeLists.txt
  cmake/ProjConfig.cmake
  cmake/ProjTest.cmake
  src/lib_proj.cmake
  test/googletest/CMakeLists.txt.in
  test/unit/CMakeLists.txt
Labels: backport 7.0

#2109 Fix working of Helmert transform between the horizontal part of 2 compoundCRS (fixes #2108)
  src/iso19111/coordinateoperation.cpp
  test/unit/test_operation.cpp
Labels: backport 6.3, backport 7.0

#2113 Database: fix registration of custom entries of grid_transformation_custom.sql for geoid grids (fixes #2112)
  data/sql/commit.sql
  data/sql/grid_transformation_custom.sql
  test/cli/testprojinfo_out.dist
Labels: backport 7.0

#2117 ESRI_WKT ingestion: make sure to identify to non-deprecated EPSG entry when possible (fixes #2116)
  src/iso19111/factory.cpp
  test/unit/test_crs.cpp
Labels: backport 7.0
