Repository OSGeo/PROJ, pull requests merged in 2020-06, with the labels that each got.

#2255 Doc: add specific explanations for lat_ts for +proj=stere, also mentions +lat_0 and +k_0
  docs/source/operations/projections/stere.rst
Labels: Documentation, backport 7.0

#2258 Doc: use Doxygen output for proj_normalize_for_visualization() to avoid duplication of info (current .rst content is outdated)
  docs/source/development/reference/functions.rst
  src/proj.h
Labels: backport 7.0

#2269 BUG: replace assert with returning data associated with errors in c_api.cpp
  src/iso19111/c_api.cpp
Labels: backport 7.1
