Repository OSGeo/PROJ, pull requests merged in 2021-05, with the labels that each got.

#2705 DOC: configure and add spelling wordlist; fix typos, apply Sphinx syntax
  ChangeLog
  NEWS
  docs/source/apps/cct.rst
  docs/source/apps/projinfo.rst
  docs/source/apps/projsync.rst
  docs/source/community/code_contributions.rst
  docs/source/community/rfc/rfc-2.rst
  docs/source/community/rfc/rfc-3.rst
  docs/source/community/rfc/rfc-4.rst
  docs/source/community/rfc/rfc-5.rst
  docs/source/conf.py
  docs/source/development/index.rst
  docs/source/development/migration.rst
  docs/source/development/quickstart.rst
  docs/source/development/reference/datatypes.rst
  docs/source/development/reference/functions.rst
  docs/source/development/reference/macros.rst
  docs/source/faq.rst
  docs/source/geodesic.rst
  docs/source/glossary.rst
  docs/source/install.rst
  docs/source/news.rst
  docs/source/operations/conversions/geoc.rst
  docs/source/operations/operations_computation.rst
  docs/source/operations/pipeline.rst
  docs/source/operations/projections/cass.rst
  docs/source/operations/projections/cc.rst
  docs/source/operations/projections/gall.rst
  docs/source/operations/projections/gnom.rst
  docs/source/operations/projections/lcc.rst
  docs/source/operations/projections/merc.rst
  docs/source/operations/projections/tmerc.rst
  docs/source/operations/projections/tobmerc.rst
  docs/source/operations/projections/utm.rst
  docs/source/operations/transformations/xyzgridshift.rst
  docs/source/resource_files.rst
  docs/source/specifications/geodetictiffgrids.rst
  docs/source/spelling_wordlist.txt
  docs/source/usage/differences.rst
  docs/source/usage/environmentvars.rst
  docs/source/usage/network.rst
  docs/source/usage/projections.rst
  docs/source/usage/quickstart.rst
  docs/source/usage/transformation.rst
  include/proj/io.hpp
  src/iso19111/c_api.cpp
  src/iso19111/coordinatesystem.cpp
  src/iso19111/factory.cpp
  src/iso19111/io.cpp
  src/iso19111/operation/concatenatedoperation.cpp
  src/iso19111/operation/coordinateoperationfactory.cpp
  src/iso19111/operation/transformation.cpp
  src/iso19111/static.cpp
  src/proj.h
  test/postinstall/test_pkg-config.sh
  test/unit/test_io.cpp
  test/unit/test_operationfactory.cpp
Labels: Documentation, backport 8.0

#2707 Backport 8.0: DOC: configure and add spelling wordlist; fix typos, apply Sphinx syntax
  ChangeLog
  NEWS
  docs/source/apps/cct.rst
  docs/source/apps/projinfo.rst
  docs/source/apps/projsync.rst
  docs/source/community/code_contributions.rst
  docs/source/community/rfc/rfc-2.rst
  docs/source/community/rfc/rfc-3.rst
  docs/source/community/rfc/rfc-4.rst
  docs/source/community/rfc/rfc-5.rst
  docs/source/conf.py
  docs/source/development/index.rst
  docs/source/development/migration.rst
  docs/source/development/quickstart.rst
  docs/source/development/reference/datatypes.rst
  docs/source/development/reference/functions.rst
  docs/source/development/reference/macros.rst
  docs/source/faq.rst
  docs/source/geodesic.rst
  docs/source/glossary.rst
  docs/source/install.rst
  docs/source/news.rst
  docs/source/operations/conversions/geoc.rst
  docs/source/operations/operations_computation.rst
  docs/source/operations/pipeline.rst
  docs/source/operations/projections/cc.rst
  docs/source/operations/projections/gall.rst
  docs/source/operations/projections/gnom.rst
  docs/source/operations/projections/lcc.rst
  docs/source/operations/projections/merc.rst
  docs/source/operations/projections/tmerc.rst
  docs/source/operations/projections/tobmerc.rst
  docs/source/operations/projections/utm.rst
  docs/source/operations/transformations/xyzgridshift.rst
  docs/source/resource_files.rst
  docs/source/specifications/geodetictiffgrids.rst
  docs/source/spelling_wordlist.txt
  docs/source/usage/differences.rst
  docs/source/usage/environmentvars.rst
  docs/source/usage/network.rst
  docs/source/usage/projections.rst
  docs/source/usage/quickstart.rst
  docs/source/usage/transformation.rst
  include/proj/io.hpp
  src/iso19111/c_api.cpp
  src/iso19111/coordinatesystem.cpp
  src/iso19111/factory.cpp
  src/iso19111/io.cpp
  src/iso19111/operation/concatenatedoperation.cpp
  src/iso19111/operation/coordinateoperationfactory.cpp
  src/iso19111/operation/transformation.cpp
  src/iso19111/static.cpp
  src/proj.h
  test/postinstall/test_pkg-config.sh
  test/unit/test_io.cpp
  test/unit/test_operationfactory.cpp
Labels: Documentation

#2715 Mention what the default +units are
  docs/source/apps/geod.rst
Labels: backport 8.0

#2726 Add projinfo example; update note Windows installation
  docs/source/apps/projinfo.rst
  docs/source/install.rst
Labels: backport 8.0
