Repository OSGeo/PROJ, pull requests merged in 2023-09, with the labels that each got.

#3867 ITRF2008: fix wrong sign for 'dry' parameter of EURA and EURA_T
  data/ITRF2008
Labels: backport 9.3

#3869 Fix build error with MSVC 2019 in /std:c++20 on NN_NO_CHECK()
  .github/workflows/windows.yml
  include/proj/util.hpp
Labels: backport 9.3

#3873 ESRI WKT import: normalize GCS_unknown to unknown and D_unknown to unknown (fixes #3871)
  src/iso19111/io.cpp
  test/unit/test_io.cpp
Labels: backport 9.3

#3764 Always use the cleanest examples.
  docs/source/apps/proj.rst
Labels: stale

#3876 CoordinateOperationFactory: deal with CompoundToCompound with a horizontal similarity transformation and a ballpark vertical (fixes #3854)
  src/4D_api.cpp
  src/iso19111/c_api.cpp
  src/iso19111/operation/coordinateoperationfactory.cpp
  src/proj_internal.h
  test/cli/testvarious
  test/cli/tv_out.dist
Labels: backport 9.3

#3880 Ellipsoid::_isEquivalentTo(): fix so that an ellipsoid of semi-major …
  src/iso19111/datum.cpp
  test/unit/test_datum.cpp
Labels: backport 9.3

#3879 isEquivalentTo(): make a datum name 'unknown' equivalent to another one
  src/iso19111/crs.cpp
  src/iso19111/datum.cpp
  src/iso19111/operation/coordinateoperationfactory.cpp
  test/unit/test_datum.cpp
Labels: backport 9.3

#3877 Doc: projections.rst: document Order of applications of parameters (fixes #3875)
  docs/source/_extensions/source_file.py
  docs/source/conf.py
  docs/source/usage/projections.rst
Labels: backport 9.3

#3878 cs2cs: fix handling of input coordinates in grad (fixes #3800)
  src/apps/cs2cs.cpp
  test/CMakeLists.txt
  test/cli/testvarious
  test/cli/tv_out.dist
  test/gigs/5102.2.gie
Labels: backport 9.3

#3889 setargv.obj is not available on uwp
  src/apps/CMakeLists.txt
Labels: backport 9.3

#3888 proj.db opening: allow opening with a URI (typically for memvfs) (fixes #3887)
  src/iso19111/factory.cpp
Labels: backport 9.3

#3893 helmert.rst: remove outdated :since: and deprecation
  docs/source/news.rst
  docs/source/operations/transformations/helmert.rst
Labels: backport master

#3896 Update cct.rst
  docs/source/apps/cct.rst
Labels: backport master

#3901 Update projections.rst
  docs/source/usage/projections.rst
Labels: backport master

#3895 Update faq.rst to mention geod
  docs/source/faq.rst
Labels: backport master

#3905 Doc: give all EPSG potential names for lon_0/lat_0/x_0/y_0 (fixes #3904)
  docs/source/operations/options/lat_0.rst
  docs/source/operations/options/lon_0.rst
  docs/source/operations/options/x_0.rst
  docs/source/operations/options/y_0.rst
Labels: backport 9.3

#3910 createOperations(): fix GeogCRS 3D with TOWGS84 to geocentric CRS (fixes #3909)
  src/iso19111/operation/singleoperation.cpp
  test/unit/test_operationfactory.cpp
Labels: backport 9.3

#3911 Test suite: fix to make it pass with ENABLE_TIFF=OFF (fixes #3900)
  .github/workflows/clang_linux.yml
  test/CMakeLists.txt
  test/unit/CMakeLists.txt
  test/unit/gie_self_tests.cpp
  test/unit/test_c_api.cpp
  test/unit/test_grids.cpp
  travis/install.sh
Labels: backport 9.3
