Repository OSGeo/PROJ, pull requests merged in 2024-11, with the labels that each got.

#4304 Fix -Wshadow warnings between parammappings.cpp and singleoperation.cpp with unity builds
  src/iso19111/operation/parammappings.cpp
Labels: backport 9.5

#4302 Fail consistently on network error and grid transformations
  src/iso19111/c_api.cpp
  src/transformations/gridshift.cpp
  src/transformations/hgridshift.cpp
  src/transformations/vgridshift.cpp
  src/transformations/xyzgridshift.cpp
  test/unit/test_network.cpp
Labels: backport 9.5, funded through GSP

#4290 CMake: use enable_testing() instead of include(CTest)
  CMakeLists.txt
Labels: funded through GSP

#4310 Database: update ESRI to ArcGIS Pro 3.4
  data/CMakeLists.txt
  data/sql/esri.sql
  scripts/build_db_from_esri.py
Labels: funded through GSP

#4312 Database: update to EPSG v11.022
  data/CMakeLists.txt
  data/sql/alias_name.sql
  data/sql/compound_crs.sql
  data/sql/grid_transformation.sql
  data/sql/metadata.sql
Labels: funded through GSP

#4320 Optimization: createOperations(): avoid database lookups for CRS (typically PROJ strings) using unknown datums
  include/proj/internal/datum_internal.hpp
  include/proj/io.hpp
  scripts/reference_exported_symbols.txt
  src/iso19111/datum.cpp
  src/iso19111/factory.cpp
  src/iso19111/io.cpp
  src/iso19111/operation/coordinateoperationfactory.cpp
  test/unit/test_operationfactory.cpp
Labels: funded through GSP

#4322 Removed leftover setting of CMAKE_REQUIRED_FLAGS
  CMakeLists.txt
Labels: backport 9.5

#4323 [9.5 branch ] Add .github/workflows/auto_tag_stable.yml
  .github/workflows/auto_tag_stable.yml
Labels: backport master

#4328 WKT1 ESRI export: fix wrong mapping of Lambert Cylindrical Equal Area to Behrmann
  scripts/build_esri_projection_mapping.py
  src/iso19111/operation/conversion.cpp
  src/iso19111/operation/esriparammappings.cpp
  test/unit/test_io.cpp
Labels: backport 9.5
