Repository OSGeo/PROJ, pull requests merged in 2024-02, with the labels that each got.

#4039 Update omerc.rst to add vital caveat about the two-point method
  docs/source/operations/projections/omerc.rst
Labels: backport 9.3

#4049 Update omerc.rst to express two points connection
  docs/source/operations/projections/omerc.rst
Labels: backport master

#4061 Add more compiler warning flags
  CMakeLists.txt
  src/iso19111/operation/conversion.cpp
  test/fuzzers/proj_crs_to_crs_fuzzer.cpp
  test/unit/gie_self_tests.cpp
  test/unit/test_c_api.cpp
Labels: RFC7: Autotools→CMake
