Repository OSGeo/PROJ, pull requests merged in 2024-03, with the labels that each got.

#4081 Update geod.rst to reduce head scratching
  docs/source/apps/geod.rst
Labels: backport master, backport 9.4

#4079 DatabaseContext::lookForGridInfo(): do not trigger network activity …
  src/iso19111/factory.cpp
  test/unit/test_network.cpp
Labels: backport 9.4

#4089 Doc: add note warning that stere/sterea are different things and …
  docs/plot/plotdefs.json
  docs/source/operations/projections/images/sterea.png
  docs/source/operations/projections/stere.rst
  docs/source/operations/projections/sterea.rst
Labels: backport master

#4104 Update roundtrip example in help text for cct
  src/apps/cct.cpp
Labels: backport 9.4

#4093 Database: update to EPSG v11.007, and other updates
  data/sql/concatenated_operation.sql
  data/sql/concatenated_operation_step.sql
  data/sql/extent.sql
  data/sql/geodetic_datum.sql
  data/sql/grid_alternatives.sql
  data/sql/grid_transformation.sql
  data/sql/helmert_transformation.sql
  data/sql/metadata.sql
  data/sql/other_transformation_custom.sql
  data/sql/proj_db_table_defs.sql
  data/sql/scope.sql
  data/sql/supersession.sql
  scripts/build_db.py
  src/iso19111/operation/singleoperation.cpp
  src/proj_constants.h
  test/cli/testprojinfo
  test/cli/testprojinfo_out.dist
  test/unit/test_factory.cpp
  test/unit/test_operationfactory.cpp
Labels: backport 9.4

#4106 Retry "Connection reset by peer"
  src/networkfilemanager.cpp
Labels: backport 9.4
