Repository OSGeo/PROJ, pull requests merged in 2025-03, with the labels that each got.

#4413 Database: update to EPSG v12.004
  data/CMakeLists.txt
  data/sql/alias_name.sql
  data/sql/conversion.sql
  data/sql/deprecation.sql
  data/sql/grid_transformation.sql
  data/sql/metadata.sql
  data/sql/projected_crs.sql
  test/unit/test_operationfactory.cpp
Labels: funded through GSP

#4414 proj_download_file(): invalidate in-memory caches related to downloaded file (for the current context)
  include/proj/internal/io_internal.hpp
  include/proj/io.hpp
  scripts/reference_exported_symbols.txt
  src/iso19111/factory.cpp
  src/networkfilemanager.cpp
  src/proj_internal.h
  test/unit/test_network.cpp
Labels: funded through GSP

#4419 Retry "SSL connection timeout"
  src/networkfilemanager.cpp
Labels: backport 9.6

#4416 Remove hashbang from bash completion.
  scripts/projinfo-bash-completion.sh
Labels: backport 9.6

#4422 Build: make sure that BUILD_SHARED_LIBS is initialized before defining DEFAULT_EMBED_RESOURCE_FILES
  CMakeLists.txt
  src/lib_proj.cmake
Labels: backport 9.6

#4427 Deal with South Orientated TMerc presented as regular TMerc but with Scale_Factor=-1
  src/iso19111/operation/conversion.cpp
  test/unit/test_operation.cpp
Labels: funded through GSP, backport 9.6

#4435 Add new words to spellchecking ignore list
  docs/source/spelling_wordlist.txt
Labels: backport 9.6

#4434 Database: update to EPSG v12.005
  data/CMakeLists.txt
  data/sql/alias_name.sql
  data/sql/compound_crs.sql
  data/sql/concatenated_operation.sql
  data/sql/conversion.sql
  data/sql/extent.sql
  data/sql/geodetic_datum.sql
  data/sql/grid_alternatives.sql
  data/sql/grid_transformation.sql
  data/sql/grid_transformation_custom.sql
  data/sql/helmert_transformation.sql
  data/sql/metadata.sql
  data/sql/supersession.sql
Labels: funded through GSP, backport 9.6

#4437 Add note about unexpected behaviour of omerc
  docs/source/operations/projections/omerc.rst
Labels: backport 9.6

#4441 Implement 'exact' authalic latitude->geographic latitude and use it in +proj=aea/cea/laea/eqearth/healpix/rhealpix
  src/auth.cpp
  src/latitudes.cpp
  src/lib_proj.cmake
  src/proj_internal.h
  src/projections/aea.cpp
  src/projections/cea.cpp
  src/projections/eqearth.cpp
  src/projections/healpix.cpp
  src/projections/laea.cpp
  src/qsfn.cpp
  test/cli/test_cs2cs_various.yaml
  test/gie/builtins.gie
Labels: funded through GSP

#4443 Add missing 'limits' and 'algorithm' includes
  .github/workflows/code_checks.yml
  scripts/detect_missing_include.sh
  src/apps/projsync.cpp
  src/crs_to_crs.cpp
  src/grids.cpp
  src/trans.cpp
  src/transformations/defmodel_impl.hpp
  src/transformations/tinshift_impl.hpp
  test/unit/test_metadata.cpp
Labels: funded through GSP, backport 9.6
