Repository OSGeo/PROJ, pull requests merged in 2025-05, with the labels that each got.

#4487 Database: update to EPSG v12.008
  data/CMakeLists.txt
  data/sql/alias_name.sql
  data/sql/compound_crs.sql
  data/sql/conversion.sql
  data/sql/extent.sql
  data/sql/geodetic_crs.sql
  data/sql/geodetic_datum.sql
  data/sql/grid_transformation.sql
  data/sql/helmert_transformation.sql
  data/sql/metadata.sql
  data/sql/projected_crs.sql
  data/sql/supersession.sql
Labels: funded through GSP, backport 9.6

#4489 Database: update ESRI to ArcGIS Pro 3.5
  .github/workflows/mac/environment.yml
  data/CMakeLists.txt
  data/sql/consistency_checks_triggers.sql
  data/sql/esri.sql
  scripts/build_db_from_esri.py
  src/iso19111/factory.cpp
  test/cli/test_projinfo.yaml
  test/unit/test_crs.cpp
  travis/install.sh
Labels: funded through GSP, backport 9.6

#4495 Database: update to EPSG v12.009
  data/CMakeLists.txt
  data/sql/alias_name.sql
  data/sql/geodetic_datum.sql
  data/sql/grid_transformation.sql
  data/sql/metadata.sql
  data/sql/show_useless_aliases.sql
  data/sql/supersession.sql
  data/sql/vertical_crs.sql
Labels: funded through GSP

#4503 Add grid alternatives for Danish DVR90->EVRF2019 grids
  data/CMakeLists.txt
  data/sql/grid_alternatives.sql
Labels: backport 9.6

#4507 Fix Windows build when both EMBED_RESOURCE_FILES and USE_ONLY_EMBEDDED_RESOURCE_FILES are set
  .github/workflows/windows.yml
  src/filemanager.cpp
Labels: backport 9.6

#4509 Make cppcheck master happy
  src/grids.cpp
  src/projections/airocean.cpp
  src/trans.cpp
  src/transformations/horner.cpp
Labels: backport 9.6

#4511 Database: update to EPSG v12.013
  data/CMakeLists.txt
  data/sql/alias_name.sql
  data/sql/compound_crs.sql
  data/sql/grid_transformation.sql
  data/sql/metadata.sql
Labels: funded through GSP
